#!/usr/bin/env python 

import subprocess,sys
import glob
from astropy.io import ascii
from astropy.table import Table
import pyPLUTO as pp
import numpy as np


fname=sys.argv[1]
cycles=sys.argv[2]


output=open(fname+".pf",'w')
output.write("System_type(0=star,1=binary,2=agn)                    2\n")
output.write("Wind_type                 3\n")	
output.write("Coord.system(0=spherical,1=cylindrical,2=spherical_polar,3=cyl_var)                    1\n")
output.write("Wind.dim.in.x_or_r.direction                     30\n")
output.write("Wind.dim.in.z_or_theta.direction                   30\n")
output.write("Number.of.wind.components 1\n") 
output.write("disk.type(0=no.disk,1=standard.flat.disk,2=vertically.extended.disk) 0\n") 
output.write("Atomic_data                         data/standard80\n")
output.write("write_atomicdata(0=no,1=yes)               0\n")        
output.write("photons_per_cycle                            100000\n")
output.write("Ionization_cycles                                "+str(cycles)+"\n")
output.write("spectrum_cycles                                   0\n")
output.write("adjust_grid(0=no,1=yes)								0\n")
output.write("Wind_ionization 9\n")
output.write("Line_transfer 3\n")
output.write("Thermal_balance_options(0=everything.on,1=no.adiabatic)                    1\n")
output.write("Disk_radiation(y=1)                               0\n")
output.write("Wind_radiation(y=1)                               1\n")
output.write("QSO_BH_radiation                               1\n")
output.write("Rad_type_for_disk(0=bb,1=models)_to_make_wind     0\n")
output.write("Rad_type_for_agn(0=bb,1=models,3=power_law,4=cloudy_table)_to_make_wind)  5\n")
output.write("mstar(msol)                                     7\n")
output.write("rstar(cm)                                     7e+08\n")
output.write("tstar                                         40000\n")
output.write("lum_agn(ergs/s) 1.7698e37\n")
output.write("agn_bremsstrahlung_temp(K) 5.6e7\n")
output.write("agn_bremsstrahlung_alpha 0.0\n")
output.write("geometry_for_pl_source 0\n")
output.write("agn_power_law_index 							0.0\n")
output.write("agn_power_law_cutoff (0)						0\n")
output.write("Torus(0=no,1=yes)								0\n")
output.write("disk.mdot(msol/yr)                            1e-08\n")
output.write("Disk.illumination.treatment 0\n")
output.write("Disk.temperature.profile(0=standard;1=readin)                    0\n")
output.write("disk.radmax(cm)                             2.4e+10\n")
output.write("wind.radmax(cm)                               1e+11\n")
output.write("wind.t.init                                   40000\n")
output.write("hydro_file "+fname+"\n")
output.write("Hydro_thetamax(degrees)                        -1\n")
output.write("filling_factor(1=smooth,<1=clumped)                    1\n")
output.write("Rad_type_for_agn(3=power_law,4=cloudy_table)_in_final_spectrum 3\n")
output.write("Rad_type_for_disk(0=bb,1=models,2=uniform)_in_final_spectrum                    0\n")
output.write("spectrum_wavemin                               1450\n")
output.write("spectrum_wavemax                               1650\n")
output.write("no_observers                                      4\n")
output.write("angle(0=pole)                                    10\n")
output.write("angle(0=pole)                                    30\n")
output.write("angle(0=pole)                                    60\n")
output.write("angle(0=pole)                                    80\n")
output.write("live.or.die(0).or.extract(anything_else)                    1\n")
output.write("spec.type(flambda(1),fnu(2),basic(other)                    1\n")
output.write("Use.standard.care.factors(1=yes)						1\n")
output.write("reverb.type 0\n")
output.write("Photon.sampling.approach           8\n")
output.write("Num.of.frequency.bands(5) 10\n")
output.write("Lowest_energy_to_be_considered(eV) 1.03333\n")
output.write("Highest_energy_to_be_considered(eV) 50000 \n")
output.write("Extra.diagnostics(0=no,1=yes)   1\n")
output.write("keep_ioncycle_windsaves()   1\n")
output.close()